export const pdfThemes = {
  // === ORIGINALS ===
  modern: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "Arial, Helvetica, sans-serif",
    primaryColor: "#000000",
    textColor: "#222222",
    ctaBg: "#00E07A",
    ctaText: "#000000",
    linkGradient: "#670fe7",
    background: "#e2e8f0",
  },
  classic: {
    font: "AdobeArabic",
    file: "AdobeArabic-Regular.ttf",
    fallback: "Georgia, serif",
    primaryColor: "#000000",
    textColor: "#444444",
    ctaBg: "#C9A86A",
    ctaText: "#ffffff",
    linkGradient: "#A17843",
    background: "#fffaf5",
  },
  bold: {
    font: "Bebas Neue",
    file: "Roboto-Regular.ttf",
    fallback: "Impact, Arial Black, sans-serif",
    primaryColor: "#000000",
    textColor: "#111111",
    ctaBg: "#EC4899",
    ctaText: "#ffffff",
    linkGradient: "#8B5CF6",
    background: "#f9e8ff",
  },
  dark: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "Arial, Helvetica, sans-serif",
    primaryColor: "#ffffff",
    textColor: "#e2e8f0",
    ctaBg: "#00E07A",
    ctaText: "#000000",
    linkGradient: "#670fe7",
    background: "#030712",
  },
  royal: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#ffffff",
    textColor: "#ffffff",
    ctaBg: "#7C3AED",
    ctaText: "#ffffff",
    linkGradient: "#4C1D95",
    background: "#2E026D",
  },
  mint: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#0f172a",
    textColor: "#082f49",
    ctaBg: "#99f6e4",
    ctaText: "#065f46",
    linkGradient: "#34d399",
    background: "#d1fae5",
  },
  sunrise: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#7c2d12",
    textColor: "#451a03",
    ctaBg: "#f97316",
    ctaText: "#ffffff",
    linkGradient: "#fb923c",
    background: "#fed7aa",
  },
  ocean: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#0c4a6e",
    textColor: "#082f49",
    ctaBg: "#38bdf8",
    ctaText: "#ffffff",
    linkGradient: "#0284c7",
    background: "#bae6fd",
  },
  rose: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#831843",
    textColor: "#9d174d",
    ctaBg: "#f43f5e",
    ctaText: "#ffffff",
    linkGradient: "#f472b6",
    background: "#fce7f3",
  },
  graphite: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#e5e7eb",
    textColor: "#9ca3af",
    ctaBg: "#6b7280",
    ctaText: "#ffffff",
    linkGradient: "#111827",
    background: "#1f2937",
  },
  forest: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#e2f7e1",
    textColor: "#d1fae5",
    ctaBg: "#15803d",
    ctaText: "#ffffff",
    linkGradient: "#166534",
    background: "#065f46",
  },
  gold: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#1f1f1f",
    textColor: "#2d2d2d",
    ctaBg: "#facc15",
    ctaText: "#000000",
    linkGradient: "#f59e0b",
    background: "#f59e0b",
  },
  lavender: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#4c1d95",
    textColor: "#6b21a8",
    ctaBg: "#c084fc",
    ctaText: "#ffffff",
    linkGradient: "#a855f7",
    background: "#c084fc",
  },
  peach: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#7c2d12",
    textColor: "#78350f",
    ctaBg: "#fb923c",
    ctaText: "#ffffff",
    linkGradient: "#f97316",
    background: "#f97316",
  },
  midnight: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#e5e7eb",
    textColor: "#cbd5e1",
    ctaBg: "#334155",
    ctaText: "#ffffff",
    linkGradient: "#1e293b",
    background: "#1e293b",
  },
  aqua: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#082f49",
    textColor: "#0c4a6e",
    ctaBg: "#0ea5e9",
    ctaText: "#ffffff",
    linkGradient: "#22d3ee",
    background: "#0ea5e9",
  },
  berry: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#fdf2f8",
    textColor: "#fce7f3",
    ctaBg: "#db2777",
    ctaText: "#ffffff",
    linkGradient: "#7e22ce",
    background: "#7e22ce",
  },
  lime: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#1a2e05",
    textColor: "#365314",
    ctaBg: "#84cc16",
    ctaText: "#000000",
    linkGradient: "#65a30d",
    background: "#65a30d",
  },
  sand: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#78350f",
    textColor: "#92400e",
    ctaBg: "#fcd34d",
    ctaText: "#000000",
    linkGradient: "#fbbf24",
    background: "#fcd34d",
  },
  sky: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#0c4a6e",
    textColor: "#082f49",
    ctaBg: "#60a5fa",
    ctaText: "#ffffff",
    linkGradient: "#3b82f6",
    background: "#60a5fa",
  },

  // === NEW THEMES ===
  copper: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#fff7ed",
    textColor: "#fff",
    ctaBg: "#92400e",
    ctaText: "#ffffff",
    linkGradient: "#f59e0b",
    background: "#b45309",
  },
  ice: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#0f172a",
    textColor: "#082f49",
    ctaBg: "#0ea5e9",
    ctaText: "#ffffff",
    linkGradient: "#0284c7",
    background: "#e0f2fe",
  },
  steel: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#f8fafc",
    textColor: "#e2e8f0",
    ctaBg: "#1e293b",
    ctaText: "#ffffff",
    linkGradient: "#94a3b8",
    background: "#475569",
  },
  coral: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#fff1f2",
    textColor: "#fff",
    ctaBg: "#f43f5e",
    ctaText: "#ffffff",
    linkGradient: "#e11d48",
    background: "#fb7185",
  },
  emerald: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#052e16",
    textColor: "#065f46",
    ctaBg: "#10b981",
    ctaText: "#ffffff",
    linkGradient: "#34d399",
    background: "#10b981",
  },
  bronze: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#fff7ed",
    textColor: "#fafaf9",
    ctaBg: "#92400e",
    ctaText: "#ffffff",
    linkGradient: "#b45309",
    background: "#78350f",
  },
  onyx: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#f1f5f9",
    textColor: "#e2e8f0",
    ctaBg: "#22d3ee",
    ctaText: "#000000",
    linkGradient: "#0ea5e9",
    background: "#0f172a",
  },
  blush: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#831843",
    textColor: "#9d174d",
    ctaBg: "#f43f5e",
    ctaText: "#ffffff",
    linkGradient: "#fb7185",
    background: "#fecdd3",
  },
    arctic: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#082f49",
    textColor: "#075985",
    ctaBg: "#0284c7",
    ctaText: "#ffffff",
    linkGradient: "#0ea5e9",
    background: "#bae6fd",
  },
  wine: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#fee2e2",
    textColor: "#fca5a5",
    ctaBg: "#991b1b",
    ctaText: "#ffffff",
    linkGradient: "#ef4444",
    background: "#7f1d1d",
  },
  charcoal: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#f9fafb",
    textColor: "#e5e7eb",
    ctaBg: "#374151",
    ctaText: "#ffffff",
    linkGradient: "#6b7280",
    background: "#111827",
  },
  platinum: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#1f2937",
    textColor: "#111827",
    ctaBg: "#9ca3af",
    ctaText: "#000000",
    linkGradient: "#d1d5db",
    background: "#f3f4f6",
  },
  amber: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#1f1f1f",
    textColor: "#111",
    ctaBg: "#f59e0b",
    ctaText: "#000000",
    linkGradient: "#facc15",
    background: "#fbbf24",
  },
    mocha: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#fef9c3",
    textColor: "#78350f",
    ctaBg: "#92400e",
    ctaText: "#ffffff",
    linkGradient: "#b45309",
    background: "#78350f",
  },

  slate: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#f8fafc",
    textColor: "#f1f5f9",
    ctaBg: "#475569",
    ctaText: "#ffffff",
    linkGradient: "#64748b",
    background: "#334155",
  },
    sapphire: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#e0f2fe",
    textColor: "#bae6fd",
    ctaBg: "#0284c7",
    ctaText: "#ffffff",
    linkGradient: "#38bdf8",
    background: "#0ea5e9",
  },

  ruby: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#fff1f2",
    textColor: "#fda4af",
    ctaBg: "#e11d48",
    ctaText: "#ffffff",
    linkGradient: "#fb7185",
    background: "#be123c",
  },
  ivory: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#1f2937",
    textColor: "#111827",
    ctaBg: "#fde68a",
    ctaText: "#000000",
    linkGradient: "#facc15",
    background: "#fefce8",
  },
    cherry: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#fee2e2",
    textColor: "#fecaca",
    ctaBg: "#b91c1c",
    ctaText: "#ffffff",
    linkGradient: "#ef4444",
    background: "#991b1b",
  },

  storm: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#f1f5f9",
    textColor: "#e2e8f0",
    ctaBg: "#475569",
    ctaText: "#ffffff",
    linkGradient: "#94a3b8",
    background: "#64748b",
  },
  sunset: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#451a03",
    textColor: "#78350f",
    ctaBg: "#f97316",
    ctaText: "#ffffff",
    linkGradient: "#fdba74",
    background: "#fb923c",
  },
   arcticBlue: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#082f49",
    textColor: "#0369a1",
    ctaBg: "#0ea5e9",
    ctaText: "#ffffff",
    linkGradient: "#38bdf8",
    background: "#7dd3fc",
  },
  teal: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#f0fdfa",
    textColor: "#cffafe",
    ctaBg: "#14b8a6",
    ctaText: "#000000",
    linkGradient: "#2dd4bf",
    background: "#0d9488",
  },
  velvet: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#faf5ff",
    textColor: "#ede9fe",
    ctaBg: "#7e22ce",
    ctaText: "#ffffff",
    linkGradient: "#a855f7",
    background: "#581c87",
  },
  tangerine: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#451a03",
    textColor: "#78350f",
    ctaBg: "#f97316",
    ctaText: "#ffffff",
    linkGradient: "#fdba74",
    background: "#f97316",
  },

  fog: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#0f172a",
    textColor: "#1e293b",
    ctaBg: "#94a3b8",
    ctaText: "#000000",
    linkGradient: "#64748b",
    background: "#cbd5e1",
  },
  carbon: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#f8fafc",
    textColor: "#e2e8f0",
    ctaBg: "#334155",
    ctaText: "#ffffff",
    linkGradient: "#64748b",
    background: "#1e293b",
  },
  moss: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#ecfdf5",
    textColor: "#d1fae5",
    ctaBg: "#166534",
    ctaText: "#ffffff",
    linkGradient: "#22c55e",
    background: "#14532d",
  },
  cream: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#1f2937",
    textColor: "#111827",
    ctaBg: "#fef08a",
    ctaText: "#000000",
    linkGradient: "#facc15",
    background: "#fef9c3",
  },
  iris: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#eef2ff",
    textColor: "#c7d2fe",
    ctaBg: "#4f46e5",
    ctaText: "#ffffff",
    linkGradient: "#818cf8",
    background: "#6366f1",
  },
  candy: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#fdf2f8",
    textColor: "#fce7f3",
    ctaBg: "#ec4899",
    ctaText: "#ffffff",
    linkGradient: "#f472b6",
    background: "#ec4899",
  },
  coffee: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#fef9c3",
    textColor: "#fef08a",
    ctaBg: "#78350f",
    ctaText: "#ffffff",
    linkGradient: "#b45309",
    background: "#6b4f4f",
  },
  periwinkle: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#1e1b4b",
    textColor: "#312e81",
    ctaBg: "#6366f1",
    ctaText: "#ffffff",
    linkGradient: "#818cf8",
    background: "#a5b4fc",
  },
  smoke: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#f9fafb",
    textColor: "#e5e7eb",
    ctaBg: "#525252",
    ctaText: "#ffffff",
    linkGradient: "#9ca3af",
    background: "#737373",
  },
  jet: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#f9fafb",
    textColor: "#d1d5db",
    ctaBg: "#262626",
    ctaText: "#ffffff",
    linkGradient: "#525252",
    background: "#0a0a0a",
  },
  rosewood: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#fef2f2",
    textColor: "#fee2e2",
    ctaBg: "#7f1d1d",
    ctaText: "#ffffff",
    linkGradient: "#b91c1c",
    background: "#4a0404",
  },
  stone: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#1c1917",
    textColor: "#292524",
    ctaBg: "#78716c",
    ctaText: "#ffffff",
    linkGradient: "#a8a29e",
    background: "#d6d3d1",
  },
  mintCream: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#052e16",
    textColor: "#064e3b",
    ctaBg: "#10b981",
    ctaText: "#ffffff",
    linkGradient: "#34d399",
    background: "#dcfce7",
  },
  navy: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#e0f2fe",
    textColor: "#bae6fd",
    ctaBg: "#3b82f6",
    ctaText: "#ffffff",
    linkGradient: "#60a5fa",
    background: "#1e3a8a",
  },
  orchid: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#faf5ff",
    textColor: "#ede9fe",
    ctaBg: "#a855f7",
    ctaText: "#ffffff",
    linkGradient: "#c084fc",
    background: "#d8b4fe",
  },
  pine: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#d1fae5",
    textColor: "#a7f3d0",
    ctaBg: "#10b981",
    ctaText: "#000000",
    linkGradient: "#34d399",
    background: "#064e3b",
  },
  wineGold: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#fef3c7",
    textColor: "#fde68a",
    ctaBg: "#854d0e",
    ctaText: "#ffffff",
    linkGradient: "#b45309",
    background: "#854d0e",
  },
    opal: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#064e3b",
    textColor: "#065f46",
    ctaBg: "#10b981",
    ctaText: "#ffffff",
    linkGradient: "#34d399",
    background: "#a7f3d0",
  },

    denim: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#e0f2fe",
    textColor: "#bfdbfe",
    ctaBg: "#3b82f6",
    ctaText: "#ffffff",
    linkGradient: "#60a5fa",
    background: "#1d4ed8",
  },

   shadow: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#f1f5f9",
    textColor: "#e2e8f0",
    ctaBg: "#262626",
    ctaText: "#ffffff",
    linkGradient: "#525252",
    background: "#171717",
  },

  honey: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#1f1f1f",
    textColor: "#111",
    ctaBg: "#fbbf24",
    ctaText: "#000000",
    linkGradient: "#f59e0b",
    background: "#facc15",
  },
  ultraviolet: {
    font: "Montserrat",
    file: "Montserrat-Regular.ttf",
    fallback: "sans-serif",
    primaryColor: "#faf5ff",
    textColor: "#ede9fe",
    ctaBg: "#7c3aed",
    ctaText: "#ffffff",
    linkGradient: "#a855f7",
    background: "#6d28d9",
  },
  
};
